version: '3.5'

services:
  python:
    build: .
    user: app
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    tmpfs:
      - /tmp
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
      PYTHONDONTWRITEBYTECODE: 'x'
    restart: unless-stopped
    networks:
      default:
        aliases:
          - homeassistant

networks:
  default:
    name: dev.eu
    ipam:
      config:
        - subnet: 10.222.0.0/16
